name: URL check

on:
  schedule:
    - cron:  '0 0 * * 1'  # once a week at 0:00 UTC
  workflow_dispatch:
    branches: [ master ]

jobs:
  check-urls:
    runs-on: macos-11
    steps:
      - uses: actions/checkout@v2
      - name: Check URLs
        run: ./check "README.md" ${{ secrets.GITHUB_TOKEN }}
